---
version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
    volumes:
      - $CONFIG_FOLDER:/config
      - $DOWNLOADS_FOLDER:/downloads
    ports:
      - $WEBUI_PORT:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
