---

ci:
    skip: [check-git-config-email]

repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.0
    hooks:
      - id: gitleaks
        args: ["detect", "--redact", "--verbose"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-symlinks
      - id: detect-private-key
      # - id: forbid-submodules in the next version

  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev:
      v1.12.3
    hooks:
      - id: check-git-config-email
        args:
          - --domains
          - gmail.com
