version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: plex
    network_mode: bridge
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Paris
      - PLEX_UID=1001
      - PLEX_GID=1001
    volumes:
      - /home/plex:/config
      - /tmp:/transcode
      - /mnt/raid:/data
