version: '2'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80
    cap_add:
      - NET_ADMIN
    dns:
      - ${SERVER_IP}
    environment:
      - ServerIP=${SERVER_IP}
      - DNS1=${DNS1}
      - DNS2=${DNS2}
    volumes:
      - ${PIHOLE_FOLDER}:/etc/pihole
      - ${DNSMASQ_FOLDER}:/etc/dnsmasq.d
