version: '2'

services:
  nextcloud-database:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    container_name: nextcloud-database
    hostname: nextcloud-database
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-server:
    image: nextcloud
    container_name: nextcloud-server
    hostname: nextcloud-server
    links:
      - nextcloud-database
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    restart: always
    depends_on:
      - nextcloud-database