version: '2'
services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=florent.clarret.lab@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=florent.clarret@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=florent.clarret.lab@gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=N0tMyPasswOrd
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_NO_PULL=true
