version: '2'
services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    hostname: radicale
    restart: always
    read_only: yes
    security_opt:
      - no-new-privileges:true
    ports:
      - ${RADICALE_PORT}:5232
    volumes:
      - ${VOLUME_DATE}:/data
      - ${VOLUME_CONFIG}:/config:ro
