version: '3.3'
services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    hostname: radicale
    restart: always
    read_only: yes
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl --fail http://localhost:5232 || exit 1
      interval: 1m
      retries: 3
    ports:
      - ${RADICALE_PORT}:5232
    volumes:
      - ${VOLUME_DATE}:/data
      - ${VOLUME_CONFIG}:/config:ro