version: '2'
services:
  portainer:
    image: portainer/portainer:alpine
    container_name: portainer
    hostname: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/portainer/data:/data
      - /srv/portainer/certs:/certs
    command:
      --ssl
      --sslcert /certs/portainer.crt
      --sslkey /certs/portainer.key
