version: '2'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    restart: always
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - MOTD=AlbionCraft
    volumes:
      - /home/minecraft/:/data