---
version: "3.3"
services:
  ddclient:
    image: linuxserver/ddclient
    hostname: ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONFIG_PATH}:/config
    restart: unless-stopped
